# KK1 - Analys av global tv-spelsförsäljning

Dataset: 'vgsales.csv'  Detta är taget från https://www.kaggle.com/datasets/gregorut/videogamesales?utm_source=chatgpt.com som i sin tur är en scrape från vgchartz.com.
Tema: global och regional försäljning av tv-spel  
Primära verktyg: pandas, numpy, matplotlib och seaborn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Inläsning och första inspektion

Först läser jag in datan och gör en snabb inspektion. Det här steget handlar inte om att dra slutsatser än, utan om att förstå materialets form: antal rader, kolumner, datatyper, saknade värden och rimliga numeriska intervall.

In [13]:
df = pd.read_csv("data/vgsales.csv")
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [ ]:
df.shape #Första antal rader andra kolumner.

In [ ]:
missing_summary = df.isna().sum()
missing_summary
# Var det saknas värden, så lite år och publishers.

In [ ]:
df.duplicated().sum() # Inga dubletter i data set:et.

Den första snabb inspektionen visar att datasetet har drygt 16000 rader och 11 kolumner. De viktigaste kolumnerna är regional och global försäljning. Två kolumner behöver tänka till på: `Year` och `Publisher`, eftersom vissa värden saknas och kanske användas direkt i analysen. Om jag vill göra någon typ av tidsdiagram måste jag komma ihåg att `Year` behöver fungera numeriskt på något sätt.

## 3. Datatvätt

In [ ]:
clean_df = df.copy() # skapar en kopia av orginalet som kan "tvättas"

clean_df["Year"] = pd.to_numeric(clean_df["Year"], errors="coerce").astype("Int64") # gör om det till heltal
clean_df["Decade"] = (clean_df["Year"] // 10 * 10).astype("Int64") # Lägger till kolumnen Decade för att kunna visa årtienden istället.

clean_df[["Name", "Platform", "Year", "Decade"]].head()
#

                       Name Platform  Year  Decade
0                Wii Sports      Wii  2006    2000
1         Super Mario Bros.      NES  1985    1980
2            Mario Kart Wii      Wii  2008    2000
3         Wii Sports Resort      Wii  2009    2000
4  Pokemon Red/Pokemon Blue       GB  1996    1990

In [18]:
clean_df.head()
missing_summary2 = clean_df.isna().sum()
missing_summary2

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
Decade          271
dtype: int64